RestaurantApp/urls.py
from django.contrib import admin
from django.urls import path, include
from restaurants.views import RestaurantListView, RestaurantDetailView, DishListView, SpotlightRestaurantsView, VisitedRestaurantView, BookmarkedRestaurantView, ToggleBookmarkView, ToggleVisitView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', RestaurantListView.as_view(), name='restaurant-list'),
    path('spotlight/', SpotlightRestaurantsView.as_view(), name = 'spotlight_restaurants'),
    path('visited/',VisitedRestaurantView.as_view(), name='visited_restaurants'),
    path('bookmarked/',BookmarkedRestaurantView.as_view(), name='bookmarked_restaurants'),
    path('restaurant/<int:pk>/', RestaurantDetailView.as_view(), name='restaurant-detail'),
    path('restaurant/<int:pk>/dishes/', DishListView.as_view(), name='dish-list'),
    path('restaurants/<int:pk>/toggle-visit/', ToggleVisitView.as_view(), name='toggle-visit'),
    path('restaurants/<int:pk>/toggle-bookmark/', ToggleBookmarkView.as_view(), name='toggle-bookmark'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

class Cuisine(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    VEG = 'veg'
    NON_VEG = 'non-veg'
    VEGAN = 'vegan'

    FOOD_TYPE_CHOICES = [
        (VEG, 'Vegetarian'),
        (NON_VEG, 'Non-Vegetarian'),
        (VEGAN, 'Vegan'),
    ]

    title = models.CharField(max_length=200)
    rating = models.DecimalField(max_digits=4, decimal_places=1, default=0.0)
    cost_for_two = models.DecimalField(max_digits=10, decimal_places=2)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=200)
    address = models.TextField()
    timings = models.CharField(max_length=200)
    food_type = models.CharField(max_length=20, choices=FOOD_TYPE_CHOICES)
    spotlight = models.BooleanField(default=False)
    cuisines = models.ManyToManyField(Cuisine)

    def __str__(self):
        return self.title

    def update_rating(self):
        reviews = self.reviews.all()
        if reviews.exists():
            average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
            if average_rating is not None:
                self.rating = average_rating
            else:
                self.rating = 0.0
            self.save()
        else:
            self.rating = 0.0
            self.save()

class Photo(models.Model):
    restaurant = models.ForeignKey(Restaurant, related_name='photos', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='restaurant_photos/')
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'Photo for {self.restaurant.title}'

class Dish(models.Model):
    VEG = 'veg'
    NON_VEG = 'non-veg'

    DISH_TYPE_CHOICES = [
        (VEG, 'Vegetarian'),
        (NON_VEG, 'Non-Vegetarian'),
    ]

    restaurant = models.ForeignKey(Restaurant, related_name='menu', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.CharField(max_length=20, choices=DISH_TYPE_CHOICES)
    image = models.ImageField(upload_to='dish_photos/', null=True, blank=True)

    def __str__(self):
        return self.name

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='reviews', on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=1)
    comment = models.TextField()

    def __str__(self):
        return f'{self.user.username} - {self.restaurant.title}'
    
class BookmarkedRestaurant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='bookmarks', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.restaurant.title}'

class VisitedRestaurant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, related_name='visits', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.restaurant.title}'

@receiver(post_save, sender=Review)
@receiver(post_delete, sender=Review)
def update_restaurant_rating(sender, instance, **kwargs):
    restaurant = instance.restaurant
    restaurant.update_rating()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Restaurant App{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'output.css' %}">
        {% block extra_head %}{% endblock %}
    </head>
    <body class="bg-gray-100 text-gray-900">
        <nav class="bg-blue-600 border-gray-200 text-white">
            <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
                <a href="{% url 'restaurant-list' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
                    <span class="self-center text-2xl font-semibold whitespace-nowrap">Restaurant App</span>
                </a>
                <button data-collapse-toggle="navbar-multi-level" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 :text-gray-400 " aria-controls="navbar-multi-level" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>dark
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                    </svg>
                </button>
                <div class="hidden bg-blue-600 w-full md:block md:w-auto" id="navbar-multi-level">
                    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 bg-blue-600">
                        <li>
                            <a href="{% url 'restaurant-list' %}" class="block py-2 px-3 text-white rounded md:bg-transparent md:p-0 " aria-current="page">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="relative">
                                <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-gray-100 hover:bg-transparent md:border-0 md:p-0 md:w-auto">{{ user.username }} <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                                </svg></button>

                                <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 ">
                                    <ul class="py-2 text-sm text-gray-700" aria-labelledby="dropdownNavbarLink">
                                        <li>
                                            <a href="{% url 'spotlight_restaurants' %}" class="block px-4 py-2 hover:bg-gray-100 ">View Spotlight Hotels</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'bookmarked_restaurants' %}" class="block px-4 py-2 hover:bg-gray-100 ">Bookmarked Hotels</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'visited_restaurants' %}" class="block px-4 py-2 hover:bg-gray-100 ">Visited Hotels</a>
                                        </li>
                                    </ul>
                                    <div class="py-1">
                                        <form method="post" action="{% url 'logout' %}">
                                            {% csrf_token %}
                                            <button type="submit" class="block w-full text-left mr-auto px-4 py-2 text-sm text-gray-700 hover:bg-red-200">
                                                Logout
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'login' %}" class="block py-2 px-3 text-white rounded md:border-0 md:p-0 ">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <main class="container mx-auto p-4">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="bg-blue-600 text-white p-4 text-center mt-10">
            <p>&copy; 2024 Restaurant App</p>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.js"></script>
        <script>
            document.getElementById('dropdownNavbarLink').addEventListener('click', function() {
                var menu = document.getElementById('dropdownNavbar');
                menu.classList.toggle('hidden');
            });

            //ajax
            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            // Function to handle toggle visit
            function toggleVisit(restaurantId) {
                fetch(`/restaurants/${restaurantId}/toggle-visit/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': getCookie('csrftoken'),
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ 'restaurant_id': restaurantId })
                })
                    .then(response => response.json())
                    .then(data => {
                        const visitButton = document.getElementById(`visit-button-${restaurantId}`);
                        if (data.visited) {
                            visitButton.textContent = 'Visited';
                            visitButton.classList.remove('bg-green-300', 'text-gray-800');
                            visitButton.classList.add('bg-green-800', 'text-white');
                        } else {
                            visitButton.textContent = 'Mark as Visited';
                            visitButton.classList.remove('bg-green-800', 'text-white');
                            visitButton.classList.add('bg-green-300', 'text-gray-800');
                        }
                    })
                    .catch(error => console.error('Error:', error));
            }

            // Function to handle toggle bookmark
            function toggleBookmark(restaurantId) {
                fetch(`/restaurants/${restaurantId}/toggle-bookmark/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': getCookie('csrftoken'),
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ 'restaurant_id': restaurantId })
                })
                    .then(response => response.json())
                    .then(data => {
                        const bookmarkButton = document.getElementById(`bookmark-button-${restaurantId}`);
                        if (data.bookmarked) {
                            bookmarkButton.textContent = 'Bookmarked';
                            bookmarkButton.classList.remove('bg-blue-300', 'text-gray-800');
                            bookmarkButton.classList.add('bg-blue-800', 'text-white');
                        } else {
                            bookmarkButton.textContent = 'Bookmark';
                            bookmarkButton.classList.remove('bg-blue-800', 'text-white');
                            bookmarkButton.classList.add('bg-blue-300', 'text-gray-800');
                        }
                    })
                    .catch(error => console.error('Error:', error));
            }

        </script>
    </body>
</html>

templates/dish_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container mx-auto mt-4 px-4">
        <h2 class="text-2xl font-bold mb-4">Dishes for {{ restaurant.title }}</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {% for dish in dishes %}
                <div class="bg-white shadow-md rounded-lg overflow-hidden">
                    {% if dish.image %}
                        <img src="{{ dish.image.url }}" alt="{{ dish.name }}" class="w-full h-56 object-cover">
                    {% else %}
                        <img src="{% static 'default-food.png' %}" alt="{{ dish.name }}" class="w-full h-56 object-cover">
                    {% endif %}
                    <div class="p-4">
                        <h3 class="text-xl font-bold mb-2">{{ dish.name }}</h3>
                        <p class="text-gray-700"><strong>Price:</strong> {{ dish.price }}</p>
                        <p class="text-gray-700"><strong>Type:</strong> {{ dish.get_dish_type_display }}</p>
                    </div>
                </div>
            {% empty %}
                <p>No dishes available for this restaurant.</p>
            {% endfor %}
        </div>
        <div class="mt-4">
            <a href="{% url 'restaurant-detail' restaurant.pk %}" class="inline-block px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Back to Restaurant Details</a>
        </div>
    </div>
{% endblock %}

templates/restaurant_common_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{view.page_title}} {% endblock %}

{% block content %}
    <h2 class="text-2xl font-bold mb-4">{{view.page_title}}</h2>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
        {% for restaurant in restaurants %}
            <div class="bg-white shadow-md rounded-lg overflow-hidden">
                <a href="{% url 'restaurant-detail' restaurant.id %}">
                    {% if restaurant.photos.first %}
                        <img src="{{ restaurant.photos.first.image.url }}" alt="{{ restaurant.title }}" class="w-full h-56 object-cover">
                    {% else %}
                        <img src="{% static 'hotel-default.jpg' %}" alt="{{ restaurant.title }}" class="w-full h-56 object-cover">
                    {% endif %}

                    <div class="p-4">
                        <h3 class="text-xl font-bold mb-2">{{ restaurant.title }}</h3>
                        <p class="text-gray-700">Rating: {{ restaurant.rating }}</p>
                        <p class="text-gray-700">Cost for Two: {{ restaurant.cost_for_two }}</p>
                        <p class="text-gray-700">{{ restaurant.location }}</p>
                        <p class="text-gray-700">{{ restaurant.address }}</p>
                        <a href="{% url 'restaurant-detail' restaurant.id %}" class="block mt-2 text-blue-500 hover:text-blue-700">View Details</a>
                    </div>
                </a>
            </div>
        {% empty %}
            <p>No {{view.page_title}} found.</p>
        {% endfor %}
    </div>
{% endblock %}

templates/restaurant_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div id="content-container" class="container mx-auto mt-4 px-4">
        <div class="flex flex-wrap -mx-4">
        <!-- Carousel on the Left -->
            <div class="w-1/2 px-4 mb-4 md:mb-0">
                <div class="relative">
                <!-- Carousel Wrapper -->
                    <div id="default-carousel" class="relative" data-carousel="static">
                    <!-- Carousel Images -->
                        <div class="overflow-hidden relative h-96 rounded-lg">
                            {% for photo in restaurant.photos.all %}
                                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                                    <img src="{{ photo.image.url }}" class="block w-full h-full object-cover" alt="{{ restaurant.title }}">
                                </div>
                            {% empty %}
                                <div class="hidden duration-700 ease-in-out" data-carousel-item>
                                    <img src="{% static 'hotel-default.jpg' %}" class="block w-full h-full object-cover" alt="Default Image">
                                </div>
                            {% endfor %}
                        </div>
                    <!-- Slider indicators -->
                        <div class="flex absolute bottom-5 left-1/2 z-30 space-x-3 -translate-x-1/2">
                            {% for photo in restaurant.photos.all %}
                                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide {{ forloop.counter }}" data-carousel-slide-to="{{ forloop.counter0 }}"></button>
                            {% endfor %}
                        </div>
                    <!-- Slider Controls -->
                        <button type="button" class="flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-prev>
                            <span class="inline-flex justify-center items-center w-8 h-8 rounded-full bg-black/30 group-hover:bg-black/50 group-focus:ring-4 group-focus:ring-black/70 group-focus:outline-none">
                                <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
                                <span class="hidden">Previous</span>
                            </span>
                        </button>
                        <button type="button" class="flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-next>
                            <span class="inline-flex justify-center items-center w-8 h-8 rounded-full bg-black/30 group-hover:bg-black/50 group-focus:ring-4 group-focus:ring-black/70 group-focus:outline-none">
                                <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                                <span class="hidden">Next</span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Restaurant Details on the Right -->
            <div class="w-1/3 px-4">
                <h2 class="text-3xl font-bold mb-2">{{ restaurant.title }}</h2>
                <p class="text-lg mb-2"><strong>Address:</strong> {{ restaurant.address }}</p>
                <p class="text-lg mb-2"><strong>Location:</strong> {{ restaurant.location }}</p>
                <p class="text-lg mb-2"><strong>Timings:</strong> {{ restaurant.timings }}</p>
                <p class="text-lg mb-2"><strong>Food Type:</strong> {{ restaurant.get_food_type_display }}</p>
                <p class="text-lg mb-2"><strong>Cost for Two:</strong> {{ restaurant.cost_for_two }}</p>
                <p class="text-lg mb-2"><strong>Rating:</strong> {{ restaurant.rating }}</p>
                <p class="text-lg mb-4"><strong>Cuisines:</strong> {{ restaurant.cuisines.all|join:", " }}</p>

                <div class="flex space-x-8 items-center">
                    <div>
                        <div>
                            <a href="{% url 'dish-list' restaurant.pk %}" class="inline-block px-6 py-3 bg-green-500 text-white rounded-lg hover:bg-green-600 w-36 text-center">View Dishes</a>
                        </div>
                    </div>

                    <div>
                    <!-- Visit Button -->
                        <button id="visit-button-{{ restaurant.id }}" onclick="toggleVisit({{ restaurant.id }})"
                                class="px-4 py-2 w-36 font-semibold rounded-md transition-colors duration-300 ease-in-out
                                       {{ visited|yesno:'bg-green-800, bg-green-300' }} {{ visited|yesno:'text-white, text-gray-800' }}
                                       hover:opacity-95">
                            {% if visited %}
                                Visited
                            {% else %}
                                Mark as Visited
                            {% endif %}
                        </button>
                    </div>

                    <div>
                    <!-- Bookmark Button -->
                        <button id="bookmark-button-{{ restaurant.id }}" onclick="toggleBookmark({{ restaurant.id }})"
                                class="px-4 py-2 w-36 font-semibold rounded-md transition-colors duration-300 ease-in-out
                                       {{ bookmarked|yesno:'bg-blue-800, bg-blue-300' }} {{ bookmarked|yesno:'text-white, text-gray-800' }}
                                       hover:opacity-95">
                            {% if bookmarked %}
                                Bookmarked
                            {% else %}
                                Bookmark
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>



        <!-- Review Modal -->
        <div id="review-modal" class="fixed inset-0 z-50 hidden bg-black/50 flex items-center justify-center">
            <div class="bg-white p-6 rounded-lg w-1/3">
                <h3 class="text-2xl font-semibold mb-4" id="modal-title">Add Review</h3>
                <form method="post" id="review-form">
                    {% csrf_token %}
                    {{ review_form.non_field_errors }}
                    <div class="mb-4">
                        <div class="flex space-x-1 mb-4">
                            {% for i in star_range %}
                                <svg
                                    class="w-8 h-8 cursor-pointer star {% if i <= user_rating %}text-yellow-300{% else %}text-gray-300{% endif %} hover:text-yellow-300"
                                    data-value="{{ i }}"
                                    aria-hidden="true"
                                    xmlns="http://www.w3.org/2000/svg"
                                    fill="currentColor"
                                    viewBox="0 0 22 20"
                                    onclick="updateRating({{ i }})">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            {% endfor %}
                        </div>
                        <input type="hidden" name="rating" id="ratingInput" value="{{ user_rating }}">
                        {{ review_form.rating.errors }}
                    </div>
                    <div class="mb-4">
                        {% render_field review_form.comment class+="block w-full mt-1 rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" %}
                        <span class="text-red-600 text-md font-semibold">{{ review_form.comment.errors }}</span>
                    </div>
                    <input type="hidden" name="review_id" id="reviewIdInput" value="">
                    <button type="submit" class="mt-4 px-6 py-3 bg-green-500 text-white rounded-lg hover:bg-green-600" id="submit-button">Submit</button>
                    <button type="button" class="mt-4 px-6 py-3 bg-red-500 text-white rounded-lg hover:bg-red-600" onclick="closeReviewModal()">Cancel</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Display Current User's Review -->
    <div class="mt-8">
        <h3 class="text-2xl font-semibold mb-4">Your Review</h3>
        {% if user_review %}
            <div class="bg-white shadow-lg rounded-lg p-4 mb-4">
                <div class="flex items-center mb-2">
                    <h5 class="text-lg font-bold mr-2">{{ user_review.user.username }}</h5>
                    <h6 class="text-gray-600">Rating: {{ user_review.rating }}</h6>
                </div>
                <p>{{ user_review.comment }}</p>
                <p class="text-sm text-gray-500">{{ user_review.created_at }}</p>
            </div>
        {% else %}
            <p>You have not written a review yet.</p>
        {% endif %}
        <div class="mt-5">
            {% if user_review %}
                <button onclick="openReviewModal({{ user_review.id }})" class="px-4 py-2 w-36 font-semibold rounded-md bg-blue-500 text-white hover:bg-blue-600">
                    Edit Review
                </button>
            {% else %}
                <button onclick="openReviewModal()" class="px-4 py-2 w-36 font-semibold rounded-md bg-green-500 text-white hover:bg-green-600">
                    Add Review
                </button>
            {% endif %}
        </div>
    </div>

    <!-- Existing Reviews -->
    <div class="mt-8">
        <h3 class="text-2xl font-semibold mb-4">Reviews</h3>
        {% for review in page_obj.object_list %}
            <div class="bg-white shadow-lg rounded-lg p-4 mb-4">
                <div class="flex items-center mb-2">
                    <h5 class="text-lg font-bold mr-2">{{ review.user.username }}</h5>
                    <h6 class="text-gray-600">Rating: {{ review.rating }}</h6>
                </div>
                <p>{{ review.comment }}</p>
                <p class="text-sm text-gray-500">{{ review.created_at }}</p>
            </div>
        {% empty %}
            <p>No reviews yet.</p>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="mt-4">
        <div class="flex justify-between">
            <div>
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600">Previous</a>
                {% endif %}
            </div>
            <div>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600">Next</a>
                {% endif %}
            </div>
        </div>
    </div>
    </div>

    <script>

        function openReviewModal(reviewId = null) {
            document.getElementById('review-modal').classList.remove('hidden');
            if (reviewId) {
                document.getElementById('reviewIdInput').value = reviewId;
                document.getElementById('modal-title').textContent = 'Edit Review';
            } else {
                document.getElementById('reviewIdInput').value = '';
                document.getElementById('modal-title').textContent = 'Add Review';
            }
        }

        function closeReviewModal() {
            document.getElementById('review-modal').classList.add('hidden');
        }


        function updateRating(value) {
            document.getElementById('ratingInput').value = value;
            const stars = document.querySelectorAll('.star');
            stars.forEach(star => {
                if (parseInt(star.getAttribute('data-value')) <= value) {
                    star.classList.add('text-yellow-300');
                    star.classList.remove('text-gray-300');
                } else {
                    star.classList.add('text-gray-300');
                    star.classList.remove('text-yellow-300');
                }
            });
        }
    </script>

{% endblock %}